const el=id=>document.getElementById(id);
let mode='login',initialized=false;
export const setupAccount={user:null,busy:false,initialize};
async function send(type,data={}){const r=await chrome.runtime.sendMessage({type,...data});if(!r?.ok)throw new Error(r?.error||'Account request failed. Please retry.');return r;}
function render(){el('setupSignedIn').hidden=!setupAccount.user;el('setupAuth').hidden=!!setupAccount.user;el('setupVerification').hidden=!setupAccount.user || setupAccount.user.verified;el('setupVerified').hidden=!setupAccount.user?.verified;el('setupAccountIdentity').textContent=setupAccount.user?`Signed in as ${setupAccount.user.email || 'your Veilance account'} · ${setupAccount.user.plan}`:'';for(const id of ['setupAuthSubmit','setupWebsite','setupRecheck','setupSignOut','setupLoginTab','setupRegisterTab'])el(id).disabled=setupAccount.busy;document.dispatchEvent(new Event('veilance:setup-account'));}
async function run(fn){if(setupAccount.busy)return;setupAccount.busy=true;render();el('setupAuthMessage').textContent='Connecting to your account…';try{await fn();}catch(e){el('setupAuthMessage').textContent=e.message;}finally{setupAccount.busy=false;el('setupPassword').value='';el('setupConfirm').value='';render();}}
async function initialize(){if(initialized)return;initialized=true;await run(async()=>{setupAccount.user=(await send('VERITY_ACCOUNT')).user;if(!setupAccount.user){try{setupAccount.user=(await send('VERITY_WEBSITE_LOGIN')).user;}catch{}}el('setupAuthMessage').textContent=setupAccount.user?'Your account is connected. Continue when you’re ready.':'Sign in, create an account, or continue with the free extension.';});}
function switchMode(next){mode=next;el('setupConfirmWrap').hidden=mode!=='register';el('setupConfirm').required=mode==='register';el('setupRegistrationNote').hidden=mode!=='register';el('setupPassword').autocomplete=mode==='register'?'new-password':'current-password';el('setupAuthSubmit').textContent=mode==='register'?'Create account':'Sign in';el('setupLoginTab').setAttribute('aria-pressed',String(mode==='login'));el('setupRegisterTab').setAttribute('aria-pressed',String(mode==='register'));el('setupAuthMessage').textContent='';}
el('setupLoginTab').addEventListener('click',()=>switchMode('login'));
el('setupRegisterTab').addEventListener('click',()=>switchMode('register'));
el('setupAuthForm').addEventListener('submit',event=>{event.preventDefault();if(mode==='register'&&el('setupPassword').value!==el('setupConfirm').value){el('setupAuthMessage').textContent='Your passwords do not match.';return;}void run(async()=>{setupAccount.user=(await send(mode==='register'?'VERITY_REGISTER':'VERITY_LOGIN',{email:el('setupEmail').value.trim(),password:el('setupPassword').value})).user;el('setupAuthMessage').textContent=mode==='register'?'Account created. Verify your email to finish account setup.':'Signed in. Continue to finish setup.';});});
el('setupWebsite').addEventListener('click',()=>void run(async()=>{setupAccount.user=(await send('VERITY_WEBSITE_LOGIN')).user;el('setupAuthMessage').textContent='Website account connected. Continue to finish setup.';}));
el('setupSignOut').addEventListener('click',()=>void run(async()=>{await send('VERITY_SIGNOUT');setupAccount.user=null;el('setupAuthMessage').textContent='Signed out. You can continue without an account.';}));

el('setupRecheck').addEventListener('click',()=>void run(async()=>{setupAccount.user=(await send('VERITY_ACCOUNT')).user;el('setupAuthMessage').textContent=setupAccount.user?.verified?'Email verified. Continue to finish setup.':'Your email is not verified yet. Enter the code on the website, then check again.';}));

document.addEventListener('visibilitychange',()=>{if(!document.hidden && setupAccount.user && !setupAccount.user.verified && !setupAccount.busy)el('setupRecheck').click();});
